//EXERCICIO 016 - ESTRUTURA DE REPETIÇÃO

//ESTRUTURA WHILE
var cont = 1; //CONTADOR
while(cont <= 6){ //TESTA PRIMEIRO, DEPOIS EXECUTA O BLOCO
    console.log(`Passo ${cont}`);
    cont++; //CONTADOR + 1. NUNCA ESQUECER ESSE COMANDO. POIS É A "FINALIZAÇÃO" DO LOOP
}

//ESTRUTURA DO..WHILE
var cont2 = 1; //CONTADOR
do{ //EXECUTA O BLOCO PRIMEIRO, TESTA DEPOIS NO FINAL
    console.log(`Passo ${cont2}`);
    cont2++; //CONTADOR + 1. NUNCA ESQUECER ESSE COMANDO. POIS É A "FINALIZAÇÃO" DO LOOP
}while(c <= 6);